---
services:
  envtester:
    build: .
    image: envtester:latest
    container_name: envtester
    environment:
      RUNNER_MODE: "${RUNNER_MODE:-query}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/LightRAG:/opt/LightRAG
      - /opt/RAGChecker:/opt/RAGChecker
      - /opt/RAGIngester:/opt/RAGIngester
    networks:
      - aibox_network
    restart: "no"

networks:
  aibox_network:
    external: true
    name: aibox_network